export const mockVerifiers = [
  {
    id: "v1",
    name: "Dr. Sarah Chen",
    expertise: "Architecture",
    affiliation: "Austin Public Works",
    rating: 4.9,
    reviews: 42,
  },
  {
    id: "v2",
    name: "Marcus Williams",
    expertise: "Arts",
    affiliation: "Austin Arts Commission",
    rating: 4.7,
    reviews: 28,
  },
  {
    id: "v3",
    name: "Elena Rodriguez",
    expertise: "Environment",
    affiliation: "EPA Region 6",
    rating: 4.8,
    reviews: 35,
  },
  {
    id: "v4",
    name: "James Park",
    expertise: "Construction",
    affiliation: "Travis County",
    rating: 4.6,
    reviews: 19,
  },
];

export const mockRecipients = [
  {
    id: "r1",
    name: "Austin Mural Collective",
    type: "Nonprofit",
    location: "Austin, TX",
    bio: "A community of over 50 local artists dedicated to transforming Austin's urban landscape through public murals.",
    website: "https://austinmuralcollective.org",
    categories: ["Murals", "Community Art", "Education"],
    totalEarned: 85000,
    completedGrants: 3,
    verificationScore: 4.8,
    avatar: "AM",
    portfolio: [],
  },
  {
    id: "r2",
    name: "Green Future Research Lab",
    type: "Research",
    location: "Houston, TX",
    bio: "Research collective focused on sustainable urban development and environmental science.",
    website: "https://greenfuturelab.org",
    categories: ["Research", "Environment"],
    totalEarned: 125000,
    completedGrants: 5,
    verificationScore: 4.9,
    avatar: "GF",
    portfolio: [],
  },
  {
    id: "r3",
    name: "Maria Santos",
    type: "Individual Artist",
    location: "San Antonio, TX",
    bio: "Mixed media artist specializing in digital art and community engagement projects.",
    website: "https://mariasantosart.com",
    categories: ["Digital Art", "Community Art"],
    totalEarned: 32000,
    completedGrants: 2,
    verificationScore: 4.6,
    avatar: "MS",
    portfolio: [],
  },
  {
    id: "r4",
    name: "EduBridge Partnership",
    type: "Nonprofit",
    location: "Dallas, TX",
    bio: "Bridging education gaps for underserved communities through innovative programs.",
    website: "https://edubridgepartnership.org",
    categories: ["Education"],
    totalEarned: 210000,
    completedGrants: 8,
    verificationScore: 4.7,
    avatar: "EP",
    portfolio: [],
  },
  {
    id: "r5",
    name: "Coastal Restoration Initiative",
    type: "Nonprofit",
    location: "Corpus Christi, TX",
    bio: "Dedicated to restoring Texas coastal ecosystems through community-led conservation.",
    website: "https://coastalrestore.tx",
    categories: ["Environment", "Research"],
    totalEarned: 95000,
    completedGrants: 4,
    verificationScore: 4.5,
    avatar: "CR",
    portfolio: [],
  },
];

export const mockGrants = [
  {
    id: "g1",
    title: "Downtown Mural Initiative 2025",
    funder: "City of Austin Arts Department",
    funderId: "f1",
    description:
      "Funding for up to 5 murals across downtown Austin. We're looking for artists who can create works that reflect Austin's diverse culture and history. Each mural should be at least 500 sq ft and durable for outdoor conditions.",
    category: "Arts & Culture",
    totalBudget: 75000,
    remaining: 45000,
    disbursed: 30000,
    status: "active",
    currency: "USDC",
    applicationDeadline: "2025-03-15",
    recipientCount: 3,
    maxRecipients: 5,
    milestones: [
      {
        id: "m1",
        name: "Design Approval",
        percentage: 20,
        amount: 15000,
        verificationNeeded: true,
        verifier: "v2",
        status: "completed",
        description: "Submit final mural designs for approval.",
      },
      {
        id: "m2",
        name: "Surface Prep & Primer",
        percentage: 30,
        amount: 22500,
        verificationNeeded: true,
        verifier: "v2",
        status: "in_review",
        description: "Complete surface preparation and primer coat.",
      },
      {
        id: "m3",
        name: "Mural Completion",
        percentage: 50,
        amount: 37500,
        verificationNeeded: true,
        verifier: "v2",
        status: "locked",
        description: "Full mural complete with final protective coat.",
      },
    ],
    requirements: ["Project proposal", "Portfolio samples", "Budget breakdown"],
    recipientType: "open",
    applications: [
      {
        id: "app1",
        recipientId: "r1",
        recipientName: "Austin Mural Collective",
        status: "approved",
        submittedAt: "2025-01-10",
        proposal:
          "We propose three large-format murals celebrating Austin's music heritage...",
      },
      {
        id: "app2",
        recipientId: "r3",
        recipientName: "Maria Santos",
        status: "pending",
        submittedAt: "2025-01-15",
        proposal:
          "My digital-meets-traditional style will bring a contemporary look to the downtown corridor...",
      },
      {
        id: "app3",
        recipientId: "r5",
        recipientName: "Coastal Restoration Initiative",
        status: "pending",
        submittedAt: "2025-01-20",
        proposal: "Environmental art that educates while beautifies...",
      },
    ],
    createdAt: "2024-12-01",
    timeline: [
      { date: "2024-12-01", event: "Grant created", type: "created" },
      { date: "2025-01-05", event: "Applications open", type: "info" },
      {
        date: "2025-01-20",
        event: "Austin Mural Collective approved",
        type: "approved",
      },
      {
        date: "2025-02-01",
        event: "$15,000 released to Austin Mural Collective",
        type: "payment",
        amount: 15000,
      },
    ],
  },
  {
    id: "g2",
    title: "Clean Energy Research Fund",
    funder: "Texas Environmental Foundation",
    funderId: "f2",
    description:
      "Supporting breakthrough research in renewable energy solutions applicable to Texas climate conditions. Priority given to solar, wind, and battery storage research with practical applications.",
    category: "Environment & Science",
    totalBudget: 200000,
    remaining: 140000,
    disbursed: 60000,
    status: "active",
    currency: "USDC",
    applicationDeadline: "2025-04-01",
    recipientCount: 2,
    maxRecipients: 3,
    milestones: [
      {
        id: "m4",
        name: "Research Proposal Accepted",
        percentage: 15,
        amount: 30000,
        verificationNeeded: false,
        status: "completed",
        description: "Detailed research plan accepted by committee.",
      },
      {
        id: "m5",
        name: "Midpoint Progress Report",
        percentage: 35,
        amount: 70000,
        verificationNeeded: true,
        verifier: "v3",
        status: "completed",
        description: "Interim report showing measurable progress.",
      },
      {
        id: "m6",
        name: "Final Research Publication",
        percentage: 50,
        amount: 100000,
        verificationNeeded: true,
        verifier: "v3",
        status: "in_review",
        description: "Peer-reviewed paper or patent submission.",
      },
    ],
    requirements: [
      "Project proposal",
      "Budget breakdown",
      "Letter of recommendation",
    ],
    recipientType: "open",
    applications: [
      {
        id: "app4",
        recipientId: "r2",
        recipientName: "Green Future Research Lab",
        status: "approved",
        submittedAt: "2025-01-08",
        proposal:
          "Our lab will investigate novel perovskite solar cell configurations for high-humidity environments...",
      },
    ],
    createdAt: "2024-11-15",
    timeline: [
      { date: "2024-11-15", event: "Grant created", type: "created" },
      {
        date: "2025-01-08",
        event: "Green Future Research Lab approved",
        type: "approved",
      },
      {
        date: "2025-01-15",
        event: "$30,000 released for Research Proposal",
        type: "payment",
        amount: 30000,
      },
      {
        date: "2025-02-10",
        event: "$70,000 released for Midpoint Report",
        type: "payment",
        amount: 70000,
      },
    ],
  },
  {
    id: "g3",
    title: "Youth Education Technology Grant",
    funder: "EduFirst Foundation",
    funderId: "f3",
    description:
      "Empowering underserved schools with technology, curriculum development, and teacher training. Focus on STEM subjects for grades 6-12.",
    category: "Education",
    totalBudget: 150000,
    remaining: 150000,
    disbursed: 0,
    status: "accepting_applications",
    currency: "USDC",
    applicationDeadline: "2025-05-30",
    recipientCount: 0,
    maxRecipients: 4,
    milestones: [
      {
        id: "m7",
        name: "Program Planning",
        percentage: 25,
        amount: 37500,
        verificationNeeded: false,
        status: "locked",
        description: "Finalize curriculum and procurement plan.",
      },
      {
        id: "m8",
        name: "Equipment Delivery",
        percentage: 25,
        amount: 37500,
        verificationNeeded: true,
        verifier: "v1",
        status: "locked",
        description:
          "Computers, tablets, and peripherals delivered and installed.",
      },
      {
        id: "m9",
        name: "Teacher Training Complete",
        percentage: 25,
        amount: 37500,
        verificationNeeded: true,
        verifier: "v1",
        status: "locked",
        description: "100% of participating teachers trained.",
      },
      {
        id: "m10",
        name: "End of Year Report",
        percentage: 25,
        amount: 37500,
        verificationNeeded: false,
        status: "locked",
        description: "Student outcomes report submitted.",
      },
    ],
    requirements: ["Project proposal", "Budget breakdown", "Portfolio samples"],
    recipientType: "open",
    applications: [],
    createdAt: "2025-01-20",
    timeline: [
      { date: "2025-01-20", event: "Grant created", type: "created" },
      { date: "2025-02-01", event: "Applications opened", type: "info" },
    ],
  },
  {
    id: "g4",
    title: "Historic Preservation & Community Revitalization",
    funder: "Travis County Heritage Fund",
    funderId: "f1",
    description:
      "Restoring historically significant buildings and spaces in Travis County to support community use.",
    category: "Community Development",
    totalBudget: 500000,
    remaining: 200000,
    disbursed: 300000,
    status: "active",
    currency: "HBAR",
    applicationDeadline: "2024-12-01",
    recipientCount: 2,
    maxRecipients: 2,
    milestones: [
      {
        id: "m11",
        name: "Historical Assessment",
        percentage: 10,
        amount: 50000,
        verificationNeeded: true,
        verifier: "v1",
        status: "completed",
        description: "Professional assessment of historic structure.",
      },
      {
        id: "m12",
        name: "Structural Work Complete",
        percentage: 40,
        amount: 200000,
        verificationNeeded: true,
        verifier: "v1",
        status: "completed",
        description: "Foundation, roof, and structural elements completed.",
      },
      {
        id: "m13",
        name: "Interior Restoration",
        percentage: 30,
        amount: 150000,
        verificationNeeded: true,
        verifier: "v4",
        status: "in_review",
        description: "Interior finishes and restorations complete.",
      },
      {
        id: "m14",
        name: "Community Opening Event",
        percentage: 20,
        amount: 100000,
        verificationNeeded: false,
        status: "locked",
        description: "Grand opening with community access confirmed.",
      },
    ],
    requirements: [
      "Project proposal",
      "Budget breakdown",
      "Letter of recommendation",
    ],
    recipientType: "invite",
    applications: [
      {
        id: "app5",
        recipientId: "r4",
        recipientName: "EduBridge Partnership",
        status: "approved",
        submittedAt: "2024-11-15",
        proposal: "We will restore the historic Eastside Community Center...",
      },
    ],
    createdAt: "2024-10-01",
    timeline: [
      { date: "2024-10-01", event: "Grant created", type: "created" },
      {
        date: "2024-11-20",
        event: "EduBridge Partnership approved",
        type: "approved",
      },
      {
        date: "2024-12-05",
        event: "$50,000 released for Historical Assessment",
        type: "payment",
        amount: 50000,
      },
      {
        date: "2025-01-15",
        event: "$200,000 released for Structural Work",
        type: "payment",
        amount: 200000,
      },
      {
        date: "2025-02-10",
        event: "$50,000 released to second recipient",
        type: "payment",
        amount: 50000,
      },
    ],
  },
  {
    id: "g5",
    title: "Community Garden Network Expansion",
    funder: "Austin Parks Foundation",
    funderId: "f2",
    description:
      "Expanding Austin's network of community gardens to improve food security and community wellness.",
    category: "Environment & Science",
    totalBudget: 60000,
    remaining: 60000,
    disbursed: 0,
    status: "accepting_applications",
    currency: "USDC",
    applicationDeadline: "2025-06-15",
    recipientCount: 0,
    maxRecipients: 6,
    milestones: [
      {
        id: "m15",
        name: "Site Preparation",
        percentage: 30,
        amount: 18000,
        verificationNeeded: true,
        verifier: "v3",
        status: "locked",
        description: "Soil testing and site prep complete.",
      },
      {
        id: "m16",
        name: "Garden Beds Installed",
        percentage: 40,
        amount: 24000,
        verificationNeeded: true,
        verifier: "v3",
        status: "locked",
        description: "Raised beds built and planted.",
      },
      {
        id: "m17",
        name: "Community Launch Event",
        percentage: 30,
        amount: 18000,
        verificationNeeded: false,
        status: "locked",
        description: "Public opening with 50+ attendees.",
      },
    ],
    requirements: ["Project proposal", "Budget breakdown"],
    recipientType: "open",
    applications: [],
    createdAt: "2025-02-01",
    timeline: [{ date: "2025-02-01", event: "Grant created", type: "created" }],
  },
  {
    id: "g6",
    title: "Digital Arts Residency Program",
    funder: "Texas Creative Industries DAO",
    funderId: "f3",
    description:
      "A 3-month paid residency for emerging digital artists to develop original works with mentorship from established professionals.",
    category: "Arts & Culture",
    totalBudget: 45000,
    remaining: 45000,
    disbursed: 0,
    status: "accepting_applications",
    currency: "HBAR",
    applicationDeadline: "2025-04-20",
    recipientCount: 0,
    maxRecipients: 3,
    milestones: [
      {
        id: "m18",
        name: "Residency Start",
        percentage: 33,
        amount: 14850,
        verificationNeeded: false,
        status: "locked",
        description: "Residency officially started.",
      },
      {
        id: "m19",
        name: "Midpoint Showcase",
        percentage: 33,
        amount: 14850,
        verificationNeeded: true,
        verifier: "v2",
        status: "locked",
        description: "Intermediate work shown to panel.",
      },
      {
        id: "m20",
        name: "Final Exhibition",
        percentage: 34,
        amount: 15300,
        verificationNeeded: true,
        verifier: "v2",
        status: "locked",
        description: "Final artworks exhibited publicly.",
      },
    ],
    requirements: ["Project proposal", "Portfolio samples"],
    recipientType: "open",
    applications: [],
    createdAt: "2025-02-10",
    timeline: [{ date: "2025-02-10", event: "Grant created", type: "created" }],
  },
  {
    id: "g7",
    title: "Affordable Housing Research Initiative",
    funder: "Texas Housing Policy Center",
    funderId: "f2",
    description:
      "Research grants for studying solutions to housing affordability in major Texas cities.",
    category: "Community Development",
    totalBudget: 300000,
    remaining: 100000,
    disbursed: 200000,
    status: "active",
    currency: "USDC",
    applicationDeadline: "2024-11-01",
    recipientCount: 3,
    maxRecipients: 3,
    milestones: [
      {
        id: "m21",
        name: "Literature Review",
        percentage: 20,
        amount: 60000,
        verificationNeeded: false,
        status: "completed",
        description: "Comprehensive literature review submitted.",
      },
      {
        id: "m22",
        name: "Field Research Phase",
        percentage: 40,
        amount: 120000,
        verificationNeeded: true,
        verifier: "v4",
        status: "completed",
        description: "Surveys and interviews conducted.",
      },
      {
        id: "m23",
        name: "Policy Brief Publication",
        percentage: 40,
        amount: 120000,
        verificationNeeded: true,
        verifier: "v4",
        status: "in_review",
        description: "Actionable policy brief published.",
      },
    ],
    requirements: [
      "Project proposal",
      "Letter of recommendation",
      "Budget breakdown",
    ],
    recipientType: "invite",
    applications: [],
    createdAt: "2024-09-01",
    timeline: [],
  },
  {
    id: "g8",
    title: "Rural Broadband Access Grant",
    funder: "Texas Digital Equity Initiative",
    funderId: "f1",
    description:
      "Connecting rural Texas communities to high-speed internet through infrastructure grants.",
    category: "Technology",
    totalBudget: 1000000,
    remaining: 0,
    disbursed: 1000000,
    status: "completed",
    currency: "USD",
    applicationDeadline: "2024-06-01",
    recipientCount: 5,
    maxRecipients: 5,
    milestones: [],
    requirements: [],
    recipientType: "open",
    applications: [],
    createdAt: "2024-01-01",
    timeline: [],
  },
  {
    id: "g9",
    title: "Indigenous Language Preservation Fund",
    funder: "Humanities Texas",
    funderId: "f3",
    description:
      "Supporting documentation, teaching, and preservation of indigenous languages in Texas.",
    category: "Arts & Culture",
    totalBudget: 80000,
    remaining: 80000,
    disbursed: 0,
    status: "accepting_applications",
    currency: "USDC",
    applicationDeadline: "2025-07-01",
    recipientCount: 0,
    maxRecipients: 4,
    milestones: [
      {
        id: "m24",
        name: "Documentation Phase",
        percentage: 50,
        amount: 40000,
        verificationNeeded: true,
        verifier: "v2",
        status: "locked",
        description: "Audio/video recordings completed.",
      },
      {
        id: "m25",
        name: "Educational Materials",
        percentage: 50,
        amount: 40000,
        verificationNeeded: false,
        status: "locked",
        description: "Teaching materials published online.",
      },
    ],
    requirements: ["Project proposal", "Portfolio samples"],
    recipientType: "open",
    applications: [],
    createdAt: "2025-02-15",
    timeline: [],
  },
  {
    id: "g10",
    title: "Small Business Recovery Fund",
    funder: "Austin Chamber of Commerce",
    funderId: "f1",
    description:
      "Emergency grants to help small businesses in Austin recover from economic disruption.",
    category: "Economic Development",
    totalBudget: 250000,
    remaining: 50000,
    disbursed: 200000,
    status: "active",
    currency: "USD",
    applicationDeadline: "2025-03-31",
    recipientCount: 8,
    maxRecipients: 10,
    milestones: [
      {
        id: "m26",
        name: "Business Plan Verified",
        percentage: 50,
        amount: 125000,
        verificationNeeded: true,
        verifier: "v4",
        status: "completed",
        description: "Verified business is operational.",
      },
      {
        id: "m27",
        name: "Recovery Milestone",
        percentage: 50,
        amount: 125000,
        verificationNeeded: true,
        verifier: "v4",
        status: "in_review",
        description: "Business shows measurable recovery.",
      },
    ],
    requirements: ["Project proposal", "Budget breakdown"],
    recipientType: "open",
    applications: [],
    createdAt: "2024-08-01",
    timeline: [],
  },
];

export const mockMilestoneSubmissions = [
  {
    id: "sub1",
    grantId: "g1",
    grantTitle: "Downtown Mural Initiative 2025",
    milestoneId: "m2",
    milestoneName: "Surface Prep & Primer",
    recipientId: "r1",
    recipientName: "Austin Mural Collective",
    amount: 22500,
    submittedAt: "2025-02-18",
    dueDate: "2025-03-01",
    status: "pending",
    notes:
      "We have completed the surface preparation for all three mural locations. Primer coat applied to 2 of 3 locations, third will be done by end of week.",
    evidenceImages: 3,
    evidenceDocuments: 1,
  },
  {
    id: "sub2",
    grantId: "g2",
    grantTitle: "Clean Energy Research Fund",
    milestoneId: "m6",
    milestoneName: "Final Research Publication",
    recipientId: "r2",
    recipientName: "Green Future Research Lab",
    amount: 100000,
    submittedAt: "2025-02-20",
    dueDate: "2025-03-15",
    status: "pending",
    notes:
      "Our paper has been submitted to Nature Energy for peer review. We have attached the preprint and all supporting data.",
    evidenceImages: 2,
    evidenceDocuments: 4,
  },
  {
    id: "sub3",
    grantId: "g4",
    grantTitle: "Historic Preservation & Community Revitalization",
    milestoneId: "m13",
    milestoneName: "Interior Restoration",
    recipientId: "r4",
    recipientName: "EduBridge Partnership",
    amount: 150000,
    submittedAt: "2025-02-15",
    dueDate: "2025-02-28",
    status: "pending",
    notes:
      "Interior restoration is complete. Period-appropriate fixtures installed, original floorboards restored, and all electrical updated to code.",
    evidenceImages: 8,
    evidenceDocuments: 2,
  },
];

export const mockTransactions = [
  {
    id: "tx1",
    date: "2025-02-01",
    type: "payment",
    amount: 15000,
    recipient: "Austin Mural Collective",
    grant: "Downtown Mural Initiative 2025",
    milestone: "Design Approval",
    currency: "USDC",
  },
  {
    id: "tx2",
    date: "2025-02-10",
    type: "payment",
    amount: 70000,
    recipient: "Green Future Research Lab",
    grant: "Clean Energy Research Fund",
    milestone: "Midpoint Progress Report",
    currency: "USDC",
  },
  {
    id: "tx3",
    date: "2025-01-15",
    type: "payment",
    amount: 30000,
    recipient: "Green Future Research Lab",
    grant: "Clean Energy Research Fund",
    milestone: "Research Proposal Accepted",
    currency: "USDC",
  },
  {
    id: "tx4",
    date: "2025-01-20",
    type: "payment",
    amount: 200000,
    recipient: "EduBridge Partnership",
    grant: "Historic Preservation",
    milestone: "Structural Work Complete",
    currency: "HBAR",
  },
  {
    id: "tx5",
    date: "2025-01-10",
    type: "payment",
    amount: 50000,
    recipient: "Coastal Restoration Initiative",
    grant: "Historic Preservation",
    milestone: "Historical Assessment",
    currency: "HBAR",
  },
];

export const mockFunderStats = {
  totalCommitted: 1025000,
  totalDisbursed: 655000,
  activeGrants: 4,
  activeRecipients: 8,
  orgName: "City of Austin",
  walletBalance: 2500000,
};
